version: "3.3"

services:
  db:
    container_name: roverbit_db
    image: "postgres:12.2"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    container_name: roverbit_app
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    volumes:
      - .:/app
      - gems:/gems
    stdin_open: true
    tty: true

volumes:
  postgres:
  gems:
