# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31177962bf9d4122fd6c0ba4337bea0e4b879c69244ffc0fa4e3aa7f4183384cca149eb871401e3e6ad16ce90be7dbb7fd8b2fc8d8d6ce05d230cda8a6a3ec8f

test:
  secret_key_base: b294757917a5fc4088b3c6376aee676f02fe5ed5fe16e2c00f0b4dab9d6e587a4cf4cedf6915ecb2320de1509f4c9d2edf66ba0345ae19bac397e149120e0847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
